// GENERATED by scripts/generate-mineral-records.mjs from src/minerals/*.json.
// Do not edit directly — update the JSON and run: node scripts/generate-mineral-records.mjs
import { defineMineral } from "./validate.js";

export const FLUORITE = defineMineral({
  "id": "fluorite",
  "name": "Fluorite",
  "formula": "CaF₂",
  "dataRevision": "sr2-1",
  "crystallography": {
    "crystalSystem": "cubic",
    "pointGroup": "m-3m",
    "setting": "cubic-standard",
    "spaceGroup": "Fm-3m",
    "unitCell": {
      "a": 5.463,
      "b": 5.463,
      "c": 5.463,
      "alpha": 90,
      "beta": 90,
      "gamma": 90
    }
  },
  "references": [
    {
      "id": "mp-2741",
      "title": "Materials Project - mp-2741: CaF2 (Cubic, Fm-3m, 225)",
      "url": "https://nextgen.materialsproject.org/materials/mp-2741",
      "notes": "Publicly accessible crystallographic data under CC-BY 4.0. Unit-cell parameter a = 5.463 Å."
    },
    {
      "id": "handbook-fluorite-v1",
      "title": "Mineral Data Publishing, Fluorite, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/fluorite.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source describes crystal luster as vitreous."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography.unitCell",
        "crystallography.crystalSystem",
        "crystallography.pointGroup",
        "crystallography.spaceGroup"
      ],
      "referenceIds": [
        "mp-2741"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits",
        "habits.*.forms.*.development",
        "crystallography.setting"
      ],
      "status": "curated",
      "derivation": "Habit form selections, preferred presentation, and development values are curated visualization parameters, not measured quantities. The declared standard setting selects the core registry basis."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-fluorite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent common fluorite varieties. The IOR approximates fluorite's refractive index, not a measured optical constant."
    }
  ],
  "appearance": [
    {
      "id": "violet",
      "luster": "vitreous",
      "name": "Violet",
      "baseColor": "#8a5cd4",
      "roughness": 0.08,
      "metalness": 0,
      "transmission": 0.8,
      "ior": 1.434,
      "absorptionColor": "#6a3cb4",
      "absorptionDensity": 0.5
    },
    {
      "id": "green",
      "luster": "vitreous",
      "name": "Green",
      "baseColor": "#3cb46a",
      "roughness": 0.1,
      "metalness": 0,
      "transmission": 0.7,
      "ior": 1.434,
      "absorptionColor": "#2a8a4a",
      "absorptionDensity": 0.6
    },
    {
      "id": "colorless",
      "luster": "vitreous",
      "name": "Colorless",
      "baseColor": "#eef0f2",
      "roughness": 0.05,
      "metalness": 0,
      "transmission": 0.9,
      "ior": 1.434,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    }
  ],
  "habits": [
    {
      "id": "cube",
      "name": "Cube",
      "description": "Cube {100} dominant; the most common fluorite habit.",
      "forms": [
        {
          "id": "a",
          "label": "Cube {100}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 0,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "o",
          "label": "Octahedron {111}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 1
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "d",
          "label": "Dodecahedron {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "mp-2741"
        }
      ]
    },
    {
      "id": "octahedron",
      "name": "Octahedron",
      "description": "Octahedron {111} dominant; common in high-temperature fluorite.",
      "forms": [
        {
          "id": "a",
          "label": "Cube {100}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 0,
            "l": 0
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "o",
          "label": "Octahedron {111}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 1
          },
          "development": 1
        },
        {
          "id": "d",
          "label": "Dodecahedron {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "mp-2741"
        }
      ]
    },
    {
      "id": "cubo-octahedron",
      "name": "Cubo-octahedron",
      "description": "Cube and octahedron co-developed; truncated-cube combination habit.",
      "forms": [
        {
          "id": "a",
          "label": "Cube {100}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 0,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "o",
          "label": "Octahedron {111}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 1
          },
          "development": 0.8
        },
        {
          "id": "d",
          "label": "Dodecahedron {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "mp-2741"
        }
      ]
    }
  ]
});

export const QUARTZ = defineMineral({
  "id": "quartz",
  "name": "Quartz",
  "formula": "SiO₂",
  "dataRevision": "sr2-1",
  "crystallography": {
    "crystalSystem": "trigonal",
    "pointGroup": "32",
    "setting": "hexagonal-standard",
    "spaceGroup": "P3_121",
    "unitCell": {
      "a": 4.913,
      "b": 4.913,
      "c": 5.405,
      "alpha": 90,
      "beta": 90,
      "gamma": 120
    }
  },
  "variants": [
    {
      "id": "right",
      "name": "Right-handed quartz",
      "description": "Space group P3_121 (No. 152); the default enantiomorph.",
      "crystallography": {
        "crystalSystem": "trigonal",
        "pointGroup": "32",
        "setting": "hexagonal-standard",
        "spaceGroup": "P3_121",
        "unitCell": {
          "a": 4.913,
          "b": 4.913,
          "c": 5.405,
          "alpha": 90,
          "beta": 90,
          "gamma": 120
        }
      },
      "references": [
        {
          "id": "mp-7000"
        }
      ]
    },
    {
      "id": "left",
      "name": "Left-handed quartz",
      "description": "Space group P3_221 (No. 154); the mirror enantiomorph.",
      "crystallography": {
        "crystalSystem": "trigonal",
        "pointGroup": "32",
        "setting": "hexagonal-standard",
        "spaceGroup": "P3_221",
        "unitCell": {
          "a": 4.913,
          "b": 4.913,
          "c": 5.405,
          "alpha": 90,
          "beta": 90,
          "gamma": 120
        }
      },
      "references": [
        {
          "id": "mp-6930"
        }
      ]
    }
  ],
  "references": [
    {
      "id": "mp-7000",
      "title": "Materials Project - mp-7000: SiO2 (Trigonal, P3_121, 152)",
      "url": "https://nextgen.materialsproject.org/materials/mp-7000",
      "notes": "Publicly accessible crystallographic data under CC-BY 4.0. Unit-cell parameters a = 4.913 Å, c = 5.405 Å for right-handed α-quartz."
    },
    {
      "id": "mp-6930",
      "title": "Materials Project - mp-6930: SiO2 (Trigonal, P3_221, 154)",
      "url": "https://nextgen.materialsproject.org/materials/mp-6930",
      "notes": "Publicly accessible crystallographic data under CC-BY 4.0. Left-handed α-quartz enantiomorph."
    },
    {
      "id": "handbook-quartz-v1.2",
      "title": "Mineral Data Publishing, Quartz, version 1.2",
      "url": "https://www.handbookofmineralogy.org/pdfs/quartz.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source describes crystal luster as vitreous."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography.unitCell",
        "crystallography.crystalSystem",
        "crystallography.pointGroup",
        "crystallography.spaceGroup",
        "variants.*.crystallography"
      ],
      "referenceIds": [
        "mp-7000",
        "mp-6930"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits",
        "habits.*.forms.*.development",
        "crystallography.setting"
      ],
      "status": "curated",
      "derivation": "Habit form selections, preferred views, and development values are curated visualization parameters, not measured quantities. The declared hexagonal setting selects the core registry basis."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-quartz-v1.2"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent common quartz varieties. IOR values are representative approximations, not measured optical constants."
    }
  ],
  "appearance": [
    {
      "id": "rock-crystal",
      "luster": "vitreous",
      "name": "Rock crystal",
      "baseColor": "#eef0f2",
      "roughness": 0.05,
      "metalness": 0,
      "transmission": 0.92,
      "ior": 1.544,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    },
    {
      "id": "amethyst",
      "luster": "vitreous",
      "name": "Amethyst",
      "baseColor": "#9b6dd4",
      "roughness": 0.1,
      "metalness": 0,
      "transmission": 0.5,
      "ior": 1.544,
      "absorptionColor": "#6b4a8f",
      "absorptionDensity": 0.5
    },
    {
      "id": "smoky",
      "luster": "vitreous",
      "name": "Smoky quartz",
      "baseColor": "#5a4a3a",
      "roughness": 0.15,
      "metalness": 0,
      "transmission": 0.35,
      "ior": 1.544,
      "absorptionColor": "#2a1a0a",
      "absorptionDensity": 1
    },
    {
      "id": "citrine",
      "luster": "vitreous",
      "name": "Citrine",
      "baseColor": "#d4a017",
      "roughness": 0.1,
      "metalness": 0,
      "transmission": 0.6,
      "ior": 1.544,
      "absorptionColor": "#b8860b",
      "absorptionDensity": 0.6
    },
    {
      "id": "rose",
      "luster": "vitreous",
      "name": "Rose quartz",
      "baseColor": "#d4a0a0",
      "roughness": 0.12,
      "metalness": 0,
      "transmission": 0.7,
      "ior": 1.544,
      "absorptionColor": "#c47070",
      "absorptionDensity": 0.4
    }
  ],
  "habits": [
    {
      "id": "prismatic",
      "name": "Prismatic (Normal)",
      "description": "Prism m dominant with rhombohedron r termination; the most common quartz habit.",
      "forms": [
        {
          "id": "m",
          "label": "Prism m {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "r",
          "label": "Rhombohedron r {10-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 1
          },
          "development": 0.8
        },
        {
          "id": "z",
          "label": "Rhombohedron z {01-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 1,
            "i": -1,
            "l": 1
          },
          "development": 0.3,
          "enabled": false
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1,
          0.4,
          0.7
        ]
      },
      "references": [
        {
          "id": "mp-7000"
        }
      ]
    },
    {
      "id": "tessin",
      "name": "Tessin",
      "description": "Prism alternating with steep rhombohedra; tapered spindle-shaped habit with steep negative rhombohedron slightly dominant.",
      "forms": [
        {
          "id": "m",
          "label": "Prism m {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "M",
          "label": "Steep rhombohedron M {20-21}",
          "indices": {
            "notation": "miller-bravais",
            "h": 2,
            "k": 0,
            "i": -2,
            "l": 1
          },
          "development": 0.85
        },
        {
          "id": "psi",
          "label": "Steep rhombohedron Ψ {02-21}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 2,
            "i": -2,
            "l": 1
          },
          "development": 0.95
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1,
          0.4,
          0.7
        ]
      },
      "references": [
        {
          "id": "mp-7000"
        }
      ]
    },
    {
      "id": "cumberland",
      "name": "Cumberland",
      "description": "Prism suppressed, rhombohedra r and z dominant; approaching bipyramidal habit.",
      "forms": [
        {
          "id": "m",
          "label": "Prism m {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 0.8
        },
        {
          "id": "r",
          "label": "Rhombohedron r {10-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 1
          },
          "development": 1
        },
        {
          "id": "z",
          "label": "Rhombohedron z {01-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 1,
            "i": -1,
            "l": 1
          },
          "development": 1
        }
      ],
      "preferredView": {
        "cameraDirection": [
          0,
          1,
          0.5
        ]
      },
      "references": [
        {
          "id": "mp-7000"
        }
      ]
    },
    {
      "id": "pseudocubic",
      "name": "Pseudocubic",
      "description": "Prism absent, rhombohedra r and z equally co-developed; pseudocubic rhombohedral habit.",
      "forms": [
        {
          "id": "m",
          "label": "Prism m {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 0.15,
          "enabled": false
        },
        {
          "id": "r",
          "label": "Rhombohedron r {10-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 1
          },
          "development": 1
        },
        {
          "id": "z",
          "label": "Rhombohedron z {01-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 1,
            "i": -1,
            "l": 1
          },
          "development": 1
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1,
          1,
          1
        ]
      },
      "references": [
        {
          "id": "mp-7000"
        }
      ]
    }
  ]
});

export const CALCITE = defineMineral({
  "id": "calcite",
  "name": "Calcite",
  "formula": "CaCO₃",
  "dataRevision": "m5-1",
  "crystallography": {
    "crystalSystem": "trigonal",
    "pointGroup": "-3m",
    "setting": "hexagonal-standard",
    "spaceGroup": "R-3c",
    "unitCell": {
      "a": 4.99,
      "b": 4.99,
      "c": 17.0615,
      "alpha": 90,
      "beta": 90,
      "gamma": 120
    }
  },
  "references": [
    {
      "id": "cod-9000095",
      "title": "Graf (1961), Crystallographic tables for the rhombohedral carbonates",
      "url": "https://www.crystallography.net/cod/9000095.html",
      "notes": "COD CC0; acquired 2026-09-16. See docs/sources/m5-acquisition.md for revision and checksum."
    },
    {
      "id": "calcite-morphology",
      "title": "Dickson (2023), Insights into the growth morphology of calcite cement",
      "url": "https://doi.org/10.1002/dep2.210",
      "notes": "CC-BY 4.0; forms in structural hexagonal axes, section 2.2."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-9000095"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits.*.forms.*.indices"
      ],
      "referenceIds": [
        "calcite-morphology"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "referenceIds": [
        "calcite-morphology"
      ],
      "status": "curated",
      "derivation": "Named idealized habit presets use documented forms. Development values, disabled forms and preferred views are curated visualization choices, not measured growth or surface-energy parameters."
    }
  ],
  "habits": [
    {
      "id": "rhombohedral",
      "name": "Rhombohedral",
      "description": "Six rhombic faces in the structural hexagonal setting.",
      "forms": [
        {
          "id": "r",
          "label": "Rhombohedron {10−14}",
          "indices": {
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 4,
            "notation": "miller-bravais"
          },
          "development": 1,
          "enabled": true
        },
        {
          "id": "v",
          "label": "Scalenohedron {21−34}",
          "indices": {
            "h": 2,
            "k": 1,
            "i": -3,
            "l": 4,
            "notation": "miller-bravais"
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "calcite-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    },
    {
      "id": "scalenohedral",
      "name": "Scalenohedral",
      "description": "Twelve scalene triangular faces in the structural hexagonal setting.",
      "forms": [
        {
          "id": "r",
          "label": "Rhombohedron {10−14}",
          "indices": {
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 4,
            "notation": "miller-bravais"
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "v",
          "label": "Scalenohedron {21−34}",
          "indices": {
            "h": 2,
            "k": 1,
            "i": -3,
            "l": 4,
            "notation": "miller-bravais"
          },
          "development": 1,
          "enabled": true
        }
      ],
      "references": [
        {
          "id": "calcite-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    }
  ]
});

export const PYRITE = defineMineral({
  "id": "pyrite",
  "name": "Pyrite",
  "formula": "FeS₂",
  "dataRevision": "sr2-1",
  "crystallography": {
    "crystalSystem": "cubic",
    "pointGroup": "m-3",
    "setting": "cubic-standard",
    "spaceGroup": "Pa-3",
    "unitCell": {
      "a": 5.4166,
      "b": 5.4166,
      "c": 5.4166,
      "alpha": 90,
      "beta": 90,
      "gamma": 90
    }
  },
  "references": [
    {
      "id": "cod-9000594",
      "title": "Bayliss (1977), Crystal structure refinement of a weakly anisotropic pyrite: cubic model",
      "url": "https://www.crystallography.net/cod/9000594.html",
      "notes": "COD CC0; acquired 2026-09-16. See docs/sources/m5-acquisition.md for revision and checksum."
    },
    {
      "id": "pyrite-morphology",
      "title": "Arrouvel and Eon (2019), Understanding the Surfaces and Crystal Growth of Pyrite FeS2",
      "url": "https://doi.org/10.1590/1980-5373-MR-2017-1140",
      "notes": "Creative Commons Attribution; Figures 2 and 3 identify cube and pyritohedron."
    },
    {
      "id": "handbook-pyrite-v1",
      "title": "Mineral Data Publishing, Pyrite, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/pyrite.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source describes luster as metallic and splendent."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-9000594"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits.*.forms.*.indices"
      ],
      "referenceIds": [
        "pyrite-morphology"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "referenceIds": [
        "pyrite-morphology"
      ],
      "status": "curated",
      "derivation": "Named idealized habit presets use documented forms. Development values, disabled forms and preferred views are curated visualization choices, not measured growth or surface-energy parameters."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-pyrite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent pyrite's metallic brass-yellow luster and tarnished surfaces. Values are not measured optical constants."
    }
  ],
  "appearance": [
    {
      "id": "brass",
      "luster": "metallic",
      "name": "Brass",
      "baseColor": "#c8a848",
      "roughness": 0.35,
      "metalness": 0.85,
      "transmission": 0,
      "ior": 1.5,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    },
    {
      "id": "tarnished",
      "luster": "metallic",
      "name": "Tarnished",
      "baseColor": "#a89048",
      "roughness": 0.5,
      "metalness": 0.8,
      "transmission": 0,
      "ior": 1.5,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    }
  ],
  "habits": [
    {
      "id": "cubic",
      "name": "Cubic",
      "description": "Six square cube faces.",
      "forms": [
        {
          "id": "a",
          "label": "Cube {100}",
          "indices": {
            "h": 1,
            "k": 0,
            "l": 0,
            "notation": "miller"
          },
          "development": 1,
          "enabled": true
        },
        {
          "id": "e",
          "label": "Pyritohedron {210}",
          "indices": {
            "h": 2,
            "k": 1,
            "l": 0,
            "notation": "miller"
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "pyrite-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    },
    {
      "id": "pyritohedral",
      "name": "Pyritohedral",
      "description": "Twelve pentagonal faces generated with pyrite point symmetry.",
      "forms": [
        {
          "id": "a",
          "label": "Cube {100}",
          "indices": {
            "h": 1,
            "k": 0,
            "l": 0,
            "notation": "miller"
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "e",
          "label": "Pyritohedron {210}",
          "indices": {
            "h": 2,
            "k": 1,
            "l": 0,
            "notation": "miller"
          },
          "development": 1,
          "enabled": true
        }
      ],
      "references": [
        {
          "id": "pyrite-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    }
  ]
});

export const ANATASE = defineMineral({
  "id": "anatase",
  "name": "Anatase",
  "formula": "TiO₂",
  "dataRevision": "m5-1",
  "crystallography": {
    "crystalSystem": "tetragonal",
    "pointGroup": "4/mmm",
    "setting": "tetragonal-standard",
    "spaceGroup": "I41/amd:1",
    "unitCell": {
      "a": 3.7845,
      "b": 3.7845,
      "c": 9.5143,
      "alpha": 90,
      "beta": 90,
      "gamma": 90
    }
  },
  "references": [
    {
      "id": "cod-9015929",
      "title": "Howard, Sabine and Dickson (1991), Structural and thermal parameters for rutile and anatase; synthetic sample",
      "url": "https://www.crystallography.net/cod/9015929.html",
      "notes": "COD CC0; acquired 2026-09-16. See docs/sources/m5-acquisition.md for revision and checksum."
    },
    {
      "id": "anatase-morphology",
      "title": "Jeantelot et al. (2018), Morphology control of anatase TiO2 for well-defined surface chemistry",
      "url": "https://doi.org/10.1039/C8CP01983E",
      "notes": "CC-BY 3.0; {101}-dominated crystals and {001}-dominated platelets. Idealized endmembers; no growth prediction."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-9015929"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits.*.forms.*.indices"
      ],
      "referenceIds": [
        "anatase-morphology"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "referenceIds": [
        "anatase-morphology"
      ],
      "status": "curated",
      "derivation": "Named idealized habit presets use documented forms. Development values, disabled forms and preferred views are curated visualization choices, not measured growth or surface-energy parameters."
    }
  ],
  "habits": [
    {
      "id": "dipyramidal",
      "name": "Dipyramidal",
      "description": "Eight triangular dipyramid faces; the ideal untruncated endmember.",
      "forms": [
        {
          "id": "p",
          "label": "Dipyramid {101}",
          "indices": {
            "h": 1,
            "k": 0,
            "l": 1,
            "notation": "miller"
          },
          "development": 1,
          "enabled": true
        },
        {
          "id": "c",
          "label": "Basal pinacoid {001}",
          "indices": {
            "h": 0,
            "k": 0,
            "l": 1,
            "notation": "miller"
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "anatase-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    },
    {
      "id": "tabular",
      "name": "Tabular",
      "description": "Basal faces dominate a plate bounded at its edges by dipyramid faces.",
      "forms": [
        {
          "id": "p",
          "label": "Dipyramid {101}",
          "indices": {
            "h": 1,
            "k": 0,
            "l": 1,
            "notation": "miller"
          },
          "development": 0.35,
          "enabled": true
        },
        {
          "id": "c",
          "label": "Basal pinacoid {001}",
          "indices": {
            "h": 0,
            "k": 0,
            "l": 1,
            "notation": "miller"
          },
          "development": 1,
          "enabled": true
        }
      ],
      "references": [
        {
          "id": "anatase-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    }
  ]
});

export const ALBITE = defineMineral({
  "id": "albite",
  "name": "Albite",
  "formula": "NaAlSi₃O₈",
  "dataRevision": "sr2-1",
  "crystallography": {
    "crystalSystem": "triclinic",
    "pointGroup": "-1",
    "setting": "triclinic-standard",
    "spaceGroup": "C-1",
    "unitCell": {
      "a": 8.138,
      "b": 12.789,
      "c": 7.156,
      "alpha": 94.33,
      "beta": 116.57,
      "gamma": 87.65
    }
  },
  "references": [
    {
      "id": "cod-2107372",
      "title": "Ribbe, Megaw, Ferguson, Taylor and Traill (1969), The albite structures, Acta Crystallographica B25, 1503-1518",
      "url": "https://www.crystallography.net/cod/2107372.html",
      "notes": "COD CC0; low albite, conventional C-centered cell. Space group C-1 (No. 2)."
    },
    {
      "id": "handbook-albite-v1",
      "title": "Mineral Data Publishing, Albite, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/albite.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source distinguishes vitreous crystal luster from pearly cleavage surfaces."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-2107372"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "status": "curated",
      "derivation": "Habit form selections use standard pinacoidal indices in the conventional feldspar cell basis. Development values, disabled forms, and preferred views are curated visualization choices, not measured growth parameters. The declared standard setting selects the core registry basis."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-albite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent common albite varieties. Values are not measured optical constants."
    }
  ],
  "appearance": [
    {
      "id": "white",
      "luster": "vitreous",
      "name": "White",
      "baseColor": "#eef0f2",
      "roughness": 0.15,
      "metalness": 0,
      "transmission": 0.6,
      "ior": 1.529,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    }
  ],
  "habits": [
    {
      "id": "tabular",
      "name": "Tabular",
      "description": "Flattened parallel to {010}; pinacoid {010} dominant with {001} and {110} bounding the edges.",
      "forms": [
        {
          "id": "b",
          "label": "Pinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "c",
          "label": "Pinacoid {001}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 0,
            "l": 1
          },
          "development": 0.4
        },
        {
          "id": "m",
          "label": "Pinacoid {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0.4
        }
      ],
      "references": [
        {
          "id": "cod-2107372"
        }
      ]
    },
    {
      "id": "prismatic",
      "name": "Prismatic",
      "description": "Elongated blocky habit with {110} and {1-10} prisms more developed; {010} and {001} subordinate.",
      "forms": [
        {
          "id": "b",
          "label": "Pinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 0.7
        },
        {
          "id": "c",
          "label": "Pinacoid {001}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 0,
            "l": 1
          },
          "development": 0.6
        },
        {
          "id": "m",
          "label": "Pinacoid {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "z",
          "label": "Pinacoid {1-10}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": -1,
            "l": 0
          },
          "development": 1
        }
      ],
      "references": [
        {
          "id": "cod-2107372"
        }
      ]
    }
  ]
});

export const GYPSUM = defineMineral({
  "id": "gypsum",
  "name": "Gypsum",
  "formula": "CaSO₄·2H₂O",
  "dataRevision": "m8-2",
  "crystallography": {
    "crystalSystem": "monoclinic",
    "pointGroup": "2/m",
    "setting": "monoclinic-b",
    "spaceGroup": "I2/a",
    "unitCell": {
      "a": 5.67,
      "b": 15.201,
      "c": 6.533,
      "alpha": 90,
      "beta": 118.6,
      "gamma": 90
    }
  },
  "references": [
    {
      "id": "cod-5000039",
      "title": "Cole and Lancucki (1974), A refinement of the crystal structure of gypsum CaSO4.2H2O, Acta Crystallographica B30, 921-929",
      "url": "https://www.crystallography.net/cod/5000039.html",
      "notes": "COD CC0; space group I2/a (No. 15), unique axis b. Unit cell a=5.67, b=15.201, c=6.533 Å, beta=118.6 deg."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-5000039"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "status": "curated",
      "derivation": "Habit form selections use standard monoclinic form indices in the I2/a cell basis. Development values, disabled forms, and preferred views are curated visualization choices, not measured growth parameters. The declared monoclinic-b setting selects the core registry basis with unique axis b."
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters selected to represent common gypsum varieties. Values are not measured optical constants."
    }
  ],
  "appearance": [
    {
      "id": "colorless",
      "name": "Colorless",
      "baseColor": "#eef0f2",
      "roughness": 0.1,
      "metalness": 0,
      "transmission": 0.7,
      "ior": 1.521,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    },
    {
      "id": "selenite",
      "name": "Selenite",
      "baseColor": "#f0f0e0",
      "roughness": 0.08,
      "metalness": 0,
      "transmission": 0.75,
      "ior": 1.521,
      "absorptionColor": "#fff8e0",
      "absorptionDensity": 0.1
    }
  ],
  "habits": [
    {
      "id": "tabular",
      "name": "Tabular (Selenite)",
      "description": "Clinopinacoid {010} dominant; flat tabular crystal bounded by {110} and {111}. The common selenite habit.",
      "forms": [
        {
          "id": "b",
          "label": "Clinopinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "m",
          "label": "Prism {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0.3
        },
        {
          "id": "o",
          "label": "Prism {111}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 1
          },
          "development": 0.3
        }
      ],
      "references": [
        {
          "id": "cod-5000039"
        }
      ]
    },
    {
      "id": "prismatic",
      "name": "Prismatic",
      "description": "Prism {110} dominant with clinodome {011} and prism {111}; elongated prismatic habit without prominent {010}.",
      "forms": [
        {
          "id": "b",
          "label": "Clinopinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "m",
          "label": "Prism {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "o",
          "label": "Prism {111}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 1
          },
          "development": 0.5
        },
        {
          "id": "d",
          "label": "Clinodome {011}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 1
          },
          "development": 0.5
        }
      ],
      "references": [
        {
          "id": "cod-5000039"
        }
      ]
    }
  ]
});

export const FORSTERITE = defineMineral({
  "id": "forsterite",
  "name": "Forsterite",
  "formula": "Mg₂SiO₄",
  "dataRevision": "sr2-1",
  "crystallography": {
    "crystalSystem": "orthorhombic",
    "pointGroup": "mmm",
    "setting": "orthorhombic-standard",
    "spaceGroup": "Pbnm",
    "unitCell": {
      "a": 4.756,
      "b": 10.207,
      "c": 5.98,
      "alpha": 90,
      "beta": 90,
      "gamma": 90
    }
  },
  "references": [
    {
      "id": "cod-9000319",
      "title": "Smyth and Hazen (1973), American Mineralogist 58, 588-593",
      "url": "https://www.crystallography.net/cod/9000319.html",
      "notes": "COD CC0; forsterite endmember, space group Pbnm (No. 62). Unit cell a=4.756, b=10.207, c=5.980 Å."
    },
    {
      "id": "handbook-forsterite-v1",
      "title": "Mineral Data Publishing, Forsterite, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/forsterite.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source describes luster as vitreous."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-9000319"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "status": "curated",
      "derivation": "Habit form selections use standard orthorhombic form indices in the Pbnm cell basis. Development values, disabled forms, and preferred views are curated visualization choices, not measured growth parameters. The declared standard setting selects the core registry basis."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-forsterite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent common olivine varieties. Values are not measured optical constants."
    }
  ],
  "appearance": [
    {
      "id": "olive",
      "luster": "vitreous",
      "name": "Olive green",
      "baseColor": "#6b8e23",
      "roughness": 0.3,
      "metalness": 0,
      "transmission": 0.3,
      "ior": 1.635,
      "absorptionColor": "#4a6b18",
      "absorptionDensity": 0.8
    },
    {
      "id": "colorless",
      "luster": "vitreous",
      "name": "Colorless",
      "baseColor": "#eef0f2",
      "roughness": 0.1,
      "metalness": 0,
      "transmission": 0.8,
      "ior": 1.635,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    }
  ],
  "habits": [
    {
      "id": "tabular",
      "name": "Tabular",
      "description": "Pinacoid {010} dominant; flattened tabular crystal bounded by {110} and {001}.",
      "forms": [
        {
          "id": "b",
          "label": "Pinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "m",
          "label": "Prism {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0.4
        },
        {
          "id": "c",
          "label": "Pinacoid {001}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 0,
            "l": 1
          },
          "development": 0.5
        }
      ],
      "references": [
        {
          "id": "cod-9000319"
        }
      ]
    },
    {
      "id": "prismatic",
      "name": "Prismatic",
      "description": "Prism {110} dominant with subordinate {010} and prism {021}; elongated prismatic habit.",
      "forms": [
        {
          "id": "b",
          "label": "Pinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 0.5
        },
        {
          "id": "m",
          "label": "Prism {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "c",
          "label": "Pinacoid {001}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 0,
            "l": 1
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "s",
          "label": "Prism {021}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 2,
            "l": 1
          },
          "development": 0.4
        }
      ],
      "references": [
        {
          "id": "cod-9000319"
        }
      ]
    }
  ]
});

export const BERYL = defineMineral({
  "id": "beryl",
  "name": "Beryl",
  "formula": "Be₃Al₂Si₆O₁₈",
  "dataRevision": "sr2-1",
  "crystallography": {
    "crystalSystem": "hexagonal",
    "pointGroup": "6/mmm",
    "setting": "hexagonal-standard",
    "spaceGroup": "P6/mcc",
    "unitCell": {
      "a": 9.208,
      "b": 9.208,
      "c": 9.188,
      "alpha": 90,
      "beta": 90,
      "gamma": 120
    }
  },
  "references": [
    {
      "id": "cod-9001018",
      "title": "Hazen, Au and Finger (1986), High-pressure crystal chemistry of beryl, American Mineralogist 71, 977-984",
      "url": "https://www.crystallography.net/cod/9001018.html",
      "notes": "COD CC0; space group P6/mcc (No. 192). Ambient-pressure sample (0.001 kbar). Unit cell a=9.208, c=9.188 Å."
    },
    {
      "id": "handbook-beryl-v1",
      "title": "Mineral Data Publishing, Beryl, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/beryl.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source reports a vitreous-to-resinous luster range. Current presets use the supported vitreous category."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-9001018"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "status": "curated",
      "derivation": "Habit form selections use standard hexagonal form indices in Miller-Bravais notation. Development values, disabled forms, and preferred views are curated visualization choices, not measured growth parameters. The declared hexagonal setting selects the core registry basis."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-beryl-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent common beryl varieties (emerald, aquamarine, goshenite). IOR values are representative approximations, not measured optical constants."
    }
  ],
  "appearance": [
    {
      "id": "emerald",
      "luster": "vitreous",
      "name": "Emerald",
      "baseColor": "#2d8a4a",
      "roughness": 0.08,
      "metalness": 0,
      "transmission": 0.7,
      "ior": 1.577,
      "absorptionColor": "#1a6b3a",
      "absorptionDensity": 0.6
    },
    {
      "id": "aquamarine",
      "luster": "vitreous",
      "name": "Aquamarine",
      "baseColor": "#5bb8d4",
      "roughness": 0.06,
      "metalness": 0,
      "transmission": 0.8,
      "ior": 1.577,
      "absorptionColor": "#3a98b4",
      "absorptionDensity": 0.4
    },
    {
      "id": "goshenite",
      "luster": "vitreous",
      "name": "Goshenite",
      "baseColor": "#eef0f2",
      "roughness": 0.05,
      "metalness": 0,
      "transmission": 0.9,
      "ior": 1.577,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    }
  ],
  "habits": [
    {
      "id": "prismatic",
      "name": "Prismatic",
      "description": "Hexagonal prism {10-10} dominant with basal pinacoid {0001} termination; the common long-prismatic beryl habit.",
      "forms": [
        {
          "id": "m",
          "label": "Prism {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "c",
          "label": "Basal pinacoid {0001}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 0,
            "i": 0,
            "l": 1
          },
          "development": 0.5
        },
        {
          "id": "p",
          "label": "Dipyramid {10-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 1
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "cod-9001018"
        }
      ]
    },
    {
      "id": "short-prismatic",
      "name": "Short prismatic",
      "description": "Prism {10-10} with dipyramid {10-11} modifying the terminations; shorter, more equant habit.",
      "forms": [
        {
          "id": "m",
          "label": "Prism {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 0.7
        },
        {
          "id": "c",
          "label": "Basal pinacoid {0001}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 0,
            "i": 0,
            "l": 1
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "p",
          "label": "Dipyramid {10-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 1
          },
          "development": 0.6
        }
      ],
      "references": [
        {
          "id": "cod-9001018"
        }
      ]
    }
  ]
});
