// GENERATED by scripts/generate-mineral-records.mjs from src/minerals/*.json.
// Do not edit directly — update the JSON and run: node scripts/generate-mineral-records.mjs
import { defineMineral } from "./validate.js";

export const FLUORITE = defineMineral({
  "id": "fluorite",
  "name": "Fluorite",
  "formula": "CaF₂",
  "dataRevision": "sr9-1",
  "crystallography": {
    "crystalSystem": "cubic",
    "pointGroup": "m-3m",
    "setting": "cubic-standard",
    "spaceGroup": "Fm-3m",
    "unitCell": {
      "a": 5.463,
      "b": 5.463,
      "c": 5.463,
      "alpha": 90,
      "beta": 90,
      "gamma": 90
    }
  },
  "references": [
    {
      "id": "mp-2741",
      "title": "Materials Project - mp-2741: CaF2 (Cubic, Fm-3m, 225)",
      "url": "https://nextgen.materialsproject.org/materials/mp-2741",
      "notes": "Publicly accessible crystallographic data under CC-BY 4.0. Unit-cell parameter a = 5.463 Å."
    },
    {
      "id": "handbook-fluorite-v1",
      "title": "Mineral Data Publishing, Fluorite, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/fluorite.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source describes crystal luster as vitreous."
    },
    {
      "id": "desai-fluorite-surfaces-1979",
      "title": "Desai (1979), Surface structures of fluorite crystals",
      "url": "https://doi.org/10.1002/crat.19790140306",
      "notes": "Public abstract; accessed 2026-09-19. Used as a factual citation only; reports growth layers parallel to natural fluorite {100} faces and distinguishes natural etch pits."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography.unitCell",
        "crystallography.crystalSystem",
        "crystallography.pointGroup",
        "crystallography.spaceGroup"
      ],
      "referenceIds": [
        "mp-2741"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits",
        "habits.*.forms.*.development",
        "crystallography.setting"
      ],
      "status": "curated",
      "derivation": "Habit form selections, preferred presentation, and development values are curated visualization parameters, not measured quantities. The declared standard setting selects the core registry basis."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-fluorite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": ["appearanceClaims.0", "appearanceClaims.1", "appearanceClaims.2"],
      "referenceIds": ["handbook-fluorite-v1"],
      "status": "reported"
    },
    {
      "coverage": ["appearanceClaims.3"],
      "referenceIds": ["desai-fluorite-surfaces-1979"],
      "status": "reported"
    },
    {
      "coverage": ["surfaceProfiles"],
      "referenceIds": ["desai-fluorite-surfaces-1979"],
      "status": "reported"
    },
    {
      "coverage": ["surfaceProfiles.*.description"],
      "status": "curated",
      "derivation": "The profile identifies a documented natural growth-face observation, not a specimen measurement. Step spacing, height, phase, density, and irregularity are renderer-owned curated values."
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent common fluorite varieties. The IOR approximates fluorite's refractive index, not a measured optical constant."
    }
  ],
  "appearance": [
    {
      "id": "violet",
      "luster": "vitreous",
      "name": "Violet",
      "baseColor": "#8a5cd4",
      "roughness": 0.08,
      "metalness": 0,
      "transmission": 0.8,
      "ior": 1.434,
      "absorptionColor": "#6a3cb4",
      "absorptionDensity": 0.5
    },
    {
      "id": "green",
      "luster": "vitreous",
      "name": "Green",
      "baseColor": "#3cb46a",
      "roughness": 0.1,
      "metalness": 0,
      "transmission": 0.7,
      "ior": 1.434,
      "absorptionColor": "#2a8a4a",
      "absorptionDensity": 0.6
    },
    {
      "id": "colorless",
      "luster": "vitreous",
      "name": "Colorless",
      "baseColor": "#eef0f2",
      "roughness": 0.05,
      "metalness": 0,
      "transmission": 0.9,
      "ior": 1.434,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    }
  ],
  "appearanceClaims": [
    {"id":"appearance.fluorite.color","property":"color","description":"Fluorite occurs colorless, white, purple, blue, green, yellow, orange, red, pink, brown, and bluish black; it is commonly zoned.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"The colour range and zoning do not define measured renderer colours.","typicality":"general"},
    {"id":"appearance.fluorite.diaphaneity","property":"diaphaneity","description":"Fluorite is reported as transparent to translucent.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"Diaphaneity does not directly determine the curated transmission value.","typicality":"general"},
    {"id":"appearance.fluorite.luster","property":"luster","description":"Fluorite has vitreous luster, becoming dull when massive.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"The whole-mineral luster observation has no growth-face selector.","typicality":"general"},
    {"id":"surface.fluorite.100-growth-steps","property":"growth-steps","description":"Natural fluorite may grow through spreading and piling growth layers parallel to {100} faces.","surfaceOrigin":"growth-face","disposition":"renderer-eligible","selector":{"formId":"a"}}
  ],
  "surfaceProfiles": [
    {"id":"fluorite.100-growth-steps","kind":"growth-steps","claimId":"surface.fluorite.100-growth-steps","surfaceOrigin":"growth-face","selector":{"formId":"a"},"description":"Natural fluorite {100} growth faces may show two-dimensional growth layers; the renderer uses a curated typical presentation and is not specimen-measured."}
  ],
  "habits": [
    {
      "id": "cube",
      "name": "Cube",
      "description": "Cube {100} dominant; the most common fluorite habit.",
      "forms": [
        {
          "id": "a",
          "label": "Cube {100}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 0,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "o",
          "label": "Octahedron {111}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 1
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "d",
          "label": "Dodecahedron {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "mp-2741"
        }
      ]
    },
    {
      "id": "octahedron",
      "name": "Octahedron",
      "description": "Octahedron {111} dominant; common in high-temperature fluorite.",
      "forms": [
        {
          "id": "a",
          "label": "Cube {100}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 0,
            "l": 0
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "o",
          "label": "Octahedron {111}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 1
          },
          "development": 1
        },
        {
          "id": "d",
          "label": "Dodecahedron {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "mp-2741"
        }
      ]
    },
    {
      "id": "cubo-octahedron",
      "name": "Cubo-octahedron",
      "description": "Cube and octahedron co-developed; truncated-cube combination habit.",
      "forms": [
        {
          "id": "a",
          "label": "Cube {100}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 0,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "o",
          "label": "Octahedron {111}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 1
          },
          "development": 0.8
        },
        {
          "id": "d",
          "label": "Dodecahedron {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "mp-2741"
        }
      ]
    }
  ]
});

export const QUARTZ = defineMineral({
  "id": "quartz",
  "name": "Quartz",
  "formula": "SiO₂",
  "dataRevision": "sr9-1",
  "crystallography": {
    "crystalSystem": "trigonal",
    "pointGroup": "32",
    "setting": "hexagonal-standard",
    "spaceGroup": "P3_121",
    "unitCell": {
      "a": 4.913,
      "b": 4.913,
      "c": 5.405,
      "alpha": 90,
      "beta": 90,
      "gamma": 120
    }
  },
  "variants": [
    {
      "id": "right",
      "name": "Right-handed quartz",
      "description": "Space group P3_121 (No. 152); the default enantiomorph.",
      "crystallography": {
        "crystalSystem": "trigonal",
        "pointGroup": "32",
        "setting": "hexagonal-standard",
        "spaceGroup": "P3_121",
        "unitCell": {
          "a": 4.913,
          "b": 4.913,
          "c": 5.405,
          "alpha": 90,
          "beta": 90,
          "gamma": 120
        }
      },
      "references": [
        {
          "id": "mp-7000"
        }
      ]
    },
    {
      "id": "left",
      "name": "Left-handed quartz",
      "description": "Space group P3_221 (No. 154); the mirror enantiomorph.",
      "crystallography": {
        "crystalSystem": "trigonal",
        "pointGroup": "32",
        "setting": "hexagonal-standard",
        "spaceGroup": "P3_221",
        "unitCell": {
          "a": 4.913,
          "b": 4.913,
          "c": 5.405,
          "alpha": 90,
          "beta": 90,
          "gamma": 120
        }
      },
      "references": [
        {
          "id": "mp-6930"
        }
      ]
    }
  ],
  "references": [
    {
      "id": "mp-7000",
      "title": "Materials Project - mp-7000: SiO2 (Trigonal, P3_121, 152)",
      "url": "https://nextgen.materialsproject.org/materials/mp-7000",
      "notes": "Publicly accessible crystallographic data under CC-BY 4.0. Unit-cell parameters a = 4.913 Å, c = 5.405 Å for right-handed α-quartz."
    },
    {
      "id": "mp-6930",
      "title": "Materials Project - mp-6930: SiO2 (Trigonal, P3_221, 154)",
      "url": "https://nextgen.materialsproject.org/materials/mp-6930",
      "notes": "Publicly accessible crystallographic data under CC-BY 4.0. Left-handed α-quartz enantiomorph."
    },
    {
      "id": "handbook-quartz-v1.2",
      "title": "Mineral Data Publishing, Quartz, version 1.2",
      "url": "https://www.handbookofmineralogy.org/pdfs/quartz.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source describes crystal luster as vitreous."
    },
    {
      "id": "gia-quartz-iridescence-2017",
      "title": "Lin et al. (2017), Causes of Iridescence in Natural Quartz",
      "url": "https://origin.prod.gia.edu/gems-gemology/spring-2017-iridescence-natural-quartz",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; documents preferential etching of periodic defects on natural quartz z faces."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography.unitCell",
        "crystallography.crystalSystem",
        "crystallography.pointGroup",
        "crystallography.spaceGroup",
        "variants.*.crystallography"
      ],
      "referenceIds": [
        "mp-7000",
        "mp-6930"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits",
        "habits.*.forms.*.development",
        "crystallography.setting"
      ],
      "status": "curated",
      "derivation": "Habit form selections, preferred views, and development values are curated visualization parameters, not measured quantities. The declared hexagonal setting selects the core registry basis."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-quartz-v1.2"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent common quartz varieties. IOR values are representative approximations, not measured optical constants."
    },
    {
      "coverage": [
        "surfaceProfiles",
        "appearanceClaims.0",
        "appearanceClaims.2"
      ],
      "referenceIds": [
        "handbook-quartz-v1.2"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearanceClaims.1"
      ],
      "referenceIds": [
        "gia-quartz-iridescence-2017"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "surfaceProfiles.*.description"
      ],
      "status": "curated",
      "derivation": "Profile text identifies a documented typical growth-face observation, not a specimen measurement. Frequency, amplitude, phase and irregularity are renderer-owned curated values."
    }
  ],
  "surfaceProfiles": [
    {
      "id": "quartz.m-prism-striations",
      "kind": "directional-striations",
      "claimId": "surface.quartz.m-striation",
      "surfaceOrigin": "growth-face",
      "selector": {
        "formId": "m"
      },
      "direction": {
        "kind": "perpendicular-to-crystal-axis",
        "axis": "c"
      },
      "description": "Typical prism m {10-10} growth-face striations, perpendicular to the c-axis; not specimen-measured."
    }
  ],
  "appearanceClaims": [
    {
      "id": "surface.quartz.m-striation",
      "property": "striations",
      "description": "Quartz prism m {10-10} growth faces are commonly striated perpendicular to the c-axis.",
      "surfaceOrigin": "growth-face",
      "disposition": "renderer-eligible",
      "selector": {
        "formId": "m"
      },
      "typicality": "common"
    },
    {
      "id": "surface.quartz.z-etching",
      "property": "etching",
      "description": "Iridescent natural quartz from the Jalgaon District has ridge-and-valley texture on minor z {01-11} faces, attributed to preferential etching of periodic defects; the ridges are parallel to the m/z face edge.",
      "surfaceOrigin": "dissolution-or-etch",
      "disposition": "candidate",
      "dispositionReason": "The documented case is locality-specific and does not establish a typical quartz renderer profile.",
      "selector": {
        "formId": "z"
      }
    },
    {
      "id": "appearance.quartz.luster",
      "property": "luster",
      "description": "Quartz crystals are reported to have vitreous luster.",
      "surfaceOrigin": "not-surface-specific",
      "disposition": "descriptive-only",
      "dispositionReason": "The general luster observation has no growth-face selector.",
      "typicality": "general"
    }
  ],
  "appearance": [
    {
      "id": "rock-crystal",
      "luster": "vitreous",
      "name": "Rock crystal",
      "baseColor": "#eef0f2",
      "roughness": 0.05,
      "metalness": 0,
      "transmission": 0.92,
      "ior": 1.544,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    },
    {
      "id": "amethyst",
      "luster": "vitreous",
      "name": "Amethyst",
      "baseColor": "#9b6dd4",
      "roughness": 0.1,
      "metalness": 0,
      "transmission": 0.5,
      "ior": 1.544,
      "absorptionColor": "#6b4a8f",
      "absorptionDensity": 0.5
    },
    {
      "id": "smoky",
      "luster": "vitreous",
      "name": "Smoky quartz",
      "baseColor": "#5a4a3a",
      "roughness": 0.15,
      "metalness": 0,
      "transmission": 0.35,
      "ior": 1.544,
      "absorptionColor": "#2a1a0a",
      "absorptionDensity": 1
    },
    {
      "id": "citrine",
      "luster": "vitreous",
      "name": "Citrine",
      "baseColor": "#d4a017",
      "roughness": 0.1,
      "metalness": 0,
      "transmission": 0.6,
      "ior": 1.544,
      "absorptionColor": "#b8860b",
      "absorptionDensity": 0.6
    },
    {
      "id": "rose",
      "luster": "vitreous",
      "name": "Rose quartz",
      "baseColor": "#d4a0a0",
      "roughness": 0.12,
      "metalness": 0,
      "transmission": 0.7,
      "ior": 1.544,
      "absorptionColor": "#c47070",
      "absorptionDensity": 0.4
    }
  ],
  "habits": [
    {
      "id": "prismatic",
      "name": "Prismatic (Normal)",
      "description": "Prism m dominant with rhombohedron r termination; the most common quartz habit.",
      "forms": [
        {
          "id": "m",
          "label": "Prism m {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "r",
          "label": "Rhombohedron r {10-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 1
          },
          "development": 0.8
        },
        {
          "id": "z",
          "label": "Rhombohedron z {01-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 1,
            "i": -1,
            "l": 1
          },
          "development": 0.3,
          "enabled": false
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1,
          0.4,
          0.7
        ]
      },
      "references": [
        {
          "id": "mp-7000"
        }
      ]
    },
    {
      "id": "tessin",
      "name": "Tessin",
      "description": "Prism alternating with steep rhombohedra; tapered spindle-shaped habit with steep negative rhombohedron slightly dominant.",
      "forms": [
        {
          "id": "m",
          "label": "Prism m {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "M",
          "label": "Steep rhombohedron M {20-21}",
          "indices": {
            "notation": "miller-bravais",
            "h": 2,
            "k": 0,
            "i": -2,
            "l": 1
          },
          "development": 0.85
        },
        {
          "id": "psi",
          "label": "Steep rhombohedron Ψ {02-21}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 2,
            "i": -2,
            "l": 1
          },
          "development": 0.95
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1,
          0.4,
          0.7
        ]
      },
      "references": [
        {
          "id": "mp-7000"
        }
      ]
    },
    {
      "id": "cumberland",
      "name": "Cumberland",
      "description": "Prism suppressed, rhombohedra r and z dominant; approaching bipyramidal habit.",
      "forms": [
        {
          "id": "m",
          "label": "Prism m {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 0.8
        },
        {
          "id": "r",
          "label": "Rhombohedron r {10-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 1
          },
          "development": 1
        },
        {
          "id": "z",
          "label": "Rhombohedron z {01-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 1,
            "i": -1,
            "l": 1
          },
          "development": 1
        }
      ],
      "preferredView": {
        "cameraDirection": [
          0,
          1,
          0.5
        ]
      },
      "references": [
        {
          "id": "mp-7000"
        }
      ]
    },
    {
      "id": "pseudocubic",
      "name": "Pseudocubic",
      "description": "Prism absent, rhombohedra r and z equally co-developed; pseudocubic rhombohedral habit.",
      "forms": [
        {
          "id": "m",
          "label": "Prism m {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 0.15,
          "enabled": false
        },
        {
          "id": "r",
          "label": "Rhombohedron r {10-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 1
          },
          "development": 1
        },
        {
          "id": "z",
          "label": "Rhombohedron z {01-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 1,
            "i": -1,
            "l": 1
          },
          "development": 1
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1,
          1,
          1
        ]
      },
      "references": [
        {
          "id": "mp-7000"
        }
      ]
    }
  ]
});

export const CALCITE = defineMineral({
  "id": "calcite",
  "name": "Calcite",
  "formula": "CaCO₃",
  "dataRevision": "sr8-2",
  "crystallography": {
    "crystalSystem": "trigonal",
    "pointGroup": "-3m",
    "setting": "hexagonal-standard",
    "spaceGroup": "R-3c",
    "unitCell": {
      "a": 4.99,
      "b": 4.99,
      "c": 17.0615,
      "alpha": 90,
      "beta": 90,
      "gamma": 120
    }
  },
  "references": [
    {
      "id": "cod-9000095",
      "title": "Graf (1961), Crystallographic tables for the rhombohedral carbonates",
      "url": "https://www.crystallography.net/cod/9000095.html",
      "notes": "COD CC0; acquired 2026-09-16. See docs/sources/m5-acquisition.md for revision and checksum."
    },
    {
      "id": "calcite-morphology",
      "title": "Dickson (2023), Insights into the growth morphology of calcite cement",
      "url": "https://doi.org/10.1002/dep2.210",
      "notes": "CC-BY 4.0; forms in structural hexagonal axes, section 2.2."
    },
    {
      "id": "handbook-calcite-v1",
      "title": "Mineral Data Publishing, Calcite, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/calcite.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; pearly luster on growth faces {0001} is separate from cleavage appearance."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-9000095"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits.*.forms.*.indices"
      ],
      "referenceIds": [
        "calcite-morphology"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "referenceIds": [
        "calcite-morphology"
      ],
      "status": "curated",
      "derivation": "Named idealized habit presets use documented forms. Development values, disabled forms and preferred views are curated visualization choices, not measured growth or surface-energy parameters."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-calcite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) for colorless and yellow calcite. They are not measured optical constants or specimen observations."
    },
    {
      "coverage": [
        "surfaceProfiles",
        "appearanceClaims"
      ],
      "referenceIds": [
        "handbook-calcite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "surfaceProfiles.*.description"
      ],
      "status": "curated",
      "derivation": "Profile text identifies a documented typical growth-face observation, not a specimen measurement. Renderer sheen values are curated and do not apply the separate cleavage claim."
    }
  ],
  "surfaceProfiles": [
    {
      "id": "calcite.0001-pearly",
      "kind": "pearly-luster",
      "claimId": "surface.calcite.0001-pearly",
      "surfaceOrigin": "growth-face",
      "selector": {
        "family": {
          "notation": "miller-bravais",
          "h": 0,
          "k": 0,
          "i": 0,
          "l": 1
        }
      },
      "description": "Typical pearly luster on calcite basal {0001} growth faces; cleavage-only appearance is intentionally excluded and this is not specimen-measured."
    }
  ],
  "appearanceClaims": [
    {
      "id": "surface.calcite.0001-pearly",
      "property": "luster",
      "description": "Calcite basal {0001} growth faces may have pearly luster.",
      "surfaceOrigin": "growth-face",
      "disposition": "renderer-eligible",
      "selector": {
        "family": {
          "notation": "miller-bravais",
          "h": 0,
          "k": 0,
          "i": 0,
          "l": 1
        }
      }
    },
    {
      "id": "surface.calcite.cleavage-pearly",
      "property": "cleavage-appearance",
      "description": "Calcite cleavage surfaces may have pearly luster.",
      "surfaceOrigin": "cleavage",
      "disposition": "descriptive-only",
      "dispositionReason": "Cleavage observations must not select generated growth faces."
    },
    {
      "id": "appearance.calcite.luster",
      "property": "luster",
      "description": "Calcite is reported to have vitreous luster apart from its pearly basal and cleavage appearances.",
      "surfaceOrigin": "not-surface-specific",
      "disposition": "descriptive-only",
      "dispositionReason": "The general luster observation has no growth-face selector.",
      "typicality": "general"
    }
  ],
  "appearance": [
    {
      "id": "colorless",
      "luster": "vitreous",
      "name": "Colorless",
      "baseColor": "#f6f3ea",
      "roughness": 0.12,
      "metalness": 0,
      "transmission": 0.65,
      "ior": 1.658,
      "absorptionColor": "#fffaf0",
      "absorptionDensity": 0
    },
    {
      "id": "yellow",
      "luster": "vitreous",
      "name": "Yellow",
      "baseColor": "#d8bd72",
      "roughness": 0.16,
      "metalness": 0,
      "transmission": 0.5,
      "ior": 1.658,
      "absorptionColor": "#b89038",
      "absorptionDensity": 0.18
    }
  ],
  "habits": [
    {
      "id": "rhombohedral",
      "name": "Rhombohedral",
      "description": "Six rhombic faces in the structural hexagonal setting.",
      "forms": [
        {
          "id": "r",
          "label": "Rhombohedron {10−14}",
          "indices": {
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 4,
            "notation": "miller-bravais"
          },
          "development": 1,
          "enabled": true
        },
        {
          "id": "v",
          "label": "Scalenohedron {21−34}",
          "indices": {
            "h": 2,
            "k": 1,
            "i": -3,
            "l": 4,
            "notation": "miller-bravais"
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "calcite-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    },
    {
      "id": "scalenohedral",
      "name": "Scalenohedral",
      "description": "Twelve scalene triangular faces in the structural hexagonal setting.",
      "forms": [
        {
          "id": "r",
          "label": "Rhombohedron {10−14}",
          "indices": {
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 4,
            "notation": "miller-bravais"
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "v",
          "label": "Scalenohedron {21−34}",
          "indices": {
            "h": 2,
            "k": 1,
            "i": -3,
            "l": 4,
            "notation": "miller-bravais"
          },
          "development": 1,
          "enabled": true
        }
      ],
      "references": [
        {
          "id": "calcite-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    }
  ]
});

export const PYRITE = defineMineral({
  "id": "pyrite",
  "name": "Pyrite",
  "formula": "FeS₂",
  "dataRevision": "sr8-2",
  "crystallography": {
    "crystalSystem": "cubic",
    "pointGroup": "m-3",
    "setting": "cubic-standard",
    "spaceGroup": "Pa-3",
    "unitCell": {
      "a": 5.4166,
      "b": 5.4166,
      "c": 5.4166,
      "alpha": 90,
      "beta": 90,
      "gamma": 90
    }
  },
  "references": [
    {
      "id": "cod-9000594",
      "title": "Bayliss (1977), Crystal structure refinement of a weakly anisotropic pyrite: cubic model",
      "url": "https://www.crystallography.net/cod/9000594.html",
      "notes": "COD CC0; acquired 2026-09-16. See docs/sources/m5-acquisition.md for revision and checksum."
    },
    {
      "id": "pyrite-morphology",
      "title": "Arrouvel and Eon (2019), Understanding the Surfaces and Crystal Growth of Pyrite FeS2",
      "url": "https://doi.org/10.1590/1980-5373-MR-2017-1140",
      "notes": "Creative Commons Attribution; Figures 2 and 3 identify cube and pyritohedron."
    },
    {
      "id": "handbook-pyrite-v1",
      "title": "Mineral Data Publishing, Pyrite, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/pyrite.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source describes luster as metallic and splendent."
    },
    {
      "id": "eb1911-pyrites",
      "title": "L. J. Spencer (1911), Pyrites, Encyclopædia Britannica, vol. 22, pp. 696–697",
      "url": "https://en.wikisource.org/wiki/1911_Encyclop%C3%A6dia_Britannica/Pyrites",
      "notes": "Public-domain historical source; accessed 2026-09-19. Used as a factual citation only; cube-face striations follow cube/pyritohedron intersection edges."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-9000594"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits.*.forms.*.indices"
      ],
      "referenceIds": [
        "pyrite-morphology"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "referenceIds": [
        "pyrite-morphology"
      ],
      "status": "curated",
      "derivation": "Named idealized habit presets use documented forms. Development values, disabled forms and preferred views are curated visualization choices, not measured growth or surface-energy parameters."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-pyrite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent pyrite's metallic brass-yellow luster and tarnished surfaces. Values are not measured optical constants."
    },
    {
      "coverage": [
        "surfaceProfiles",
        "appearanceClaims"
      ],
      "referenceIds": [
        "eb1911-pyrites",
        "handbook-pyrite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "surfaceProfiles.*.description"
      ],
      "status": "curated",
      "derivation": "Profile text identifies a documented typical growth-face observation, not a specimen measurement. Frequency, amplitude, phase and irregularity are renderer-owned curated values."
    }
  ],
  "surfaceProfiles": [
    {
      "id": "pyrite.100-cube-striations",
      "kind": "directional-striations",
      "claimId": "surface.pyrite.100-striation",
      "surfaceOrigin": "growth-face",
      "selector": {
        "formId": "a"
      },
      "direction": {
        "kind": "intersection-edge",
        "otherFamily": {
          "notation": "miller",
          "h": 2,
          "k": 1,
          "l": 0
        }
      },
      "description": "Typical cube {100} growth-face striations parallel to cube/pyritohedron {210} intersection edges; not specimen-measured."
    }
  ],
  "appearanceClaims": [
    {
      "id": "surface.pyrite.100-striation",
      "property": "striations",
      "description": "Pyrite cube {100} growth faces may be striated parallel to their intersections with pyritohedron {210} faces.",
      "surfaceOrigin": "growth-face",
      "disposition": "renderer-eligible",
      "selector": {
        "formId": "a"
      }
    },
    {
      "id": "appearance.pyrite.luster",
      "property": "luster",
      "description": "Pyrite is reported to have metallic to splendent luster.",
      "surfaceOrigin": "not-surface-specific",
      "disposition": "descriptive-only",
      "dispositionReason": "The general luster observation has no growth-face selector.",
      "typicality": "general"
    }
  ],
  "appearance": [
    {
      "id": "brass",
      "luster": "metallic",
      "name": "Brass",
      "baseColor": "#c8a848",
      "roughness": 0.35,
      "metalness": 0.85,
      "transmission": 0,
      "ior": 1.5,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    },
    {
      "id": "tarnished",
      "luster": "metallic",
      "name": "Tarnished",
      "baseColor": "#a89048",
      "roughness": 0.5,
      "metalness": 0.8,
      "transmission": 0,
      "ior": 1.5,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    }
  ],
  "habits": [
    {
      "id": "cubic",
      "name": "Cubic",
      "description": "Six square cube faces.",
      "forms": [
        {
          "id": "a",
          "label": "Cube {100}",
          "indices": {
            "h": 1,
            "k": 0,
            "l": 0,
            "notation": "miller"
          },
          "development": 1,
          "enabled": true
        },
        {
          "id": "e",
          "label": "Pyritohedron {210}",
          "indices": {
            "h": 2,
            "k": 1,
            "l": 0,
            "notation": "miller"
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "pyrite-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    },
    {
      "id": "pyritohedral",
      "name": "Pyritohedral",
      "description": "Twelve pentagonal faces generated with pyrite point symmetry.",
      "forms": [
        {
          "id": "a",
          "label": "Cube {100}",
          "indices": {
            "h": 1,
            "k": 0,
            "l": 0,
            "notation": "miller"
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "e",
          "label": "Pyritohedron {210}",
          "indices": {
            "h": 2,
            "k": 1,
            "l": 0,
            "notation": "miller"
          },
          "development": 1,
          "enabled": true
        }
      ],
      "references": [
        {
          "id": "pyrite-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    }
  ]
});

export const ANATASE = defineMineral({
  "id": "anatase",
  "name": "Anatase",
  "formula": "TiO₂",
  "dataRevision": "sr8-2",
  "crystallography": {
    "crystalSystem": "tetragonal",
    "pointGroup": "4/mmm",
    "setting": "tetragonal-standard",
    "spaceGroup": "I41/amd:1",
    "unitCell": {
      "a": 3.7845,
      "b": 3.7845,
      "c": 9.5143,
      "alpha": 90,
      "beta": 90,
      "gamma": 90
    }
  },
  "references": [
    {
      "id": "cod-9015929",
      "title": "Howard, Sabine and Dickson (1991), Structural and thermal parameters for rutile and anatase; synthetic sample",
      "url": "https://www.crystallography.net/cod/9015929.html",
      "notes": "COD CC0; acquired 2026-09-16. See docs/sources/m5-acquisition.md for revision and checksum."
    },
    {
      "id": "anatase-morphology",
      "title": "Jeantelot et al. (2018), Morphology control of anatase TiO2 for well-defined surface chemistry",
      "url": "https://doi.org/10.1039/C8CP01983E",
      "notes": "CC-BY 3.0; {101}-dominated crystals and {001}-dominated platelets. Idealized endmembers; no growth prediction."
    },
    {
      "id": "handbook-anatase-v1",
      "title": "Mineral Data Publishing, Anatase, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/anatase.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; luster is reported as adamantine to splendent, metallic, with colors including brown, yellow, blue, and nearly colorless."
    },
    {
      "id": "usgs-anatase-striations-1107b",
      "title": "U.S. Geological Survey, Heavy Minerals as Guides to Uranium-Vanadium Ore Deposits in the Morrison Formation, Colorado, Bulletin 1107-B",
      "url": "https://pubs.usgs.gov/bul/1107b/report.pdf",
      "notes": "Publicly accessible government report; accessed 2026-09-19. Used as a factual citation only; reports striations on some pyramidal anatase faces in the documented Colorado material."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-9015929"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits.*.forms.*.indices"
      ],
      "referenceIds": [
        "anatase-morphology"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "referenceIds": [
        "anatase-morphology"
      ],
      "status": "curated",
      "derivation": "Named idealized habit presets use documented forms. Development values, disabled forms and preferred views are curated visualization choices, not measured growth or surface-energy parameters."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-anatase-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": ["appearanceClaims.0", "appearanceClaims.1", "appearanceClaims.2"],
      "referenceIds": ["handbook-anatase-v1"],
      "status": "reported"
    },
    {
      "coverage": ["appearanceClaims.3"],
      "referenceIds": ["usgs-anatase-striations-1107b"],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters for indigo-blue and golden-brown anatase, both colors reported for the mineral. The supported metallic category represents the source's reported luster range, including metallic; it does not assert that every anatase specimen is metallic. Numeric values are not measured optical constants."
    }
  ],
  "appearance": [
    {
      "id": "indigo",
      "luster": "metallic",
      "name": "Indigo blue",
      "baseColor": "#244f9e",
      "roughness": 0.1,
      "metalness": 0.12,
      "transmission": 0.3,
      "ior": 2.52,
      "absorptionColor": "#12295b",
      "absorptionDensity": 0.24
    },
    {
      "id": "golden",
      "luster": "metallic",
      "name": "Golden brown",
      "baseColor": "#9b6a31",
      "roughness": 0.2,
      "metalness": 0.25,
      "transmission": 0.2,
      "ior": 2.52,
      "absorptionColor": "#6e421c",
      "absorptionDensity": 0.3
    }
  ],
  "appearanceClaims": [
    {"id":"appearance.anatase.color","property":"color","description":"Anatase is reported brown, yellow, reddish brown, indigo, black, pale green, pale lilac, gray, and rarely nearly colorless.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"The colour range does not define a measured renderer colour.","typicality":"general"},
    {"id":"appearance.anatase.diaphaneity","property":"diaphaneity","description":"Anatase ranges from transparent when light coloured to nearly opaque when deeply coloured.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"Diaphaneity does not directly determine the curated transmission value.","typicality":"general"},
    {"id":"appearance.anatase.luster","property":"luster","description":"Anatase luster ranges from adamantine to splendent or metallic.","surfaceOrigin":"not-surface-specific","disposition":"blocked","dispositionReason":"The current luster vocabulary has no adamantine or splendent category, and a material mapping needs review.","typicality":"general"},
    {"id":"surface.anatase.pyramid-striation","property":"striations","description":"Some pyramidal anatase crystals from the documented Colorado material have closely spaced striations parallel to basal-pinacoid edges.","surfaceOrigin":"unknown","disposition":"candidate","dispositionReason":"The report is locality-specific and does not resolve a pyramid family or a renderer direction in the shipped basis."}
  ],
  "habits": [
    {
      "id": "dipyramidal",
      "name": "Dipyramidal",
      "description": "Eight triangular dipyramid faces; the ideal untruncated endmember.",
      "forms": [
        {
          "id": "p",
          "label": "Dipyramid {101}",
          "indices": {
            "h": 1,
            "k": 0,
            "l": 1,
            "notation": "miller"
          },
          "development": 1,
          "enabled": true
        },
        {
          "id": "c",
          "label": "Basal pinacoid {001}",
          "indices": {
            "h": 0,
            "k": 0,
            "l": 1,
            "notation": "miller"
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "anatase-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    },
    {
      "id": "tabular",
      "name": "Tabular",
      "description": "Basal faces dominate a plate bounded at its edges by dipyramid faces.",
      "forms": [
        {
          "id": "p",
          "label": "Dipyramid {101}",
          "indices": {
            "h": 1,
            "k": 0,
            "l": 1,
            "notation": "miller"
          },
          "development": 0.35,
          "enabled": true
        },
        {
          "id": "c",
          "label": "Basal pinacoid {001}",
          "indices": {
            "h": 0,
            "k": 0,
            "l": 1,
            "notation": "miller"
          },
          "development": 1,
          "enabled": true
        }
      ],
      "references": [
        {
          "id": "anatase-morphology"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    }
  ]
});

export const ALBITE = defineMineral({
  "id": "albite",
  "name": "Albite",
  "formula": "NaAlSi₃O₈",
  "dataRevision": "sr8-1",
  "crystallography": {
    "crystalSystem": "triclinic",
    "pointGroup": "-1",
    "setting": "triclinic-standard",
    "spaceGroup": "C-1",
    "unitCell": {
      "a": 8.138,
      "b": 12.789,
      "c": 7.156,
      "alpha": 94.33,
      "beta": 116.57,
      "gamma": 87.65
    }
  },
  "references": [
    {
      "id": "cod-2107372",
      "title": "Ribbe, Megaw, Ferguson, Taylor and Traill (1969), The albite structures, Acta Crystallographica B25, 1503-1518",
      "url": "https://www.crystallography.net/cod/2107372.html",
      "notes": "COD CC0; low albite, conventional C-centered cell. Space group C-1 (No. 2)."
    },
    {
      "id": "handbook-albite-v1",
      "title": "Mineral Data Publishing, Albite, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/albite.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source distinguishes vitreous crystal luster from pearly cleavage surfaces."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-2107372"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "status": "curated",
      "derivation": "Habit form selections use standard pinacoidal indices in the conventional feldspar cell basis. Development values, disabled forms, and preferred views are curated visualization choices, not measured growth parameters. The declared standard setting selects the core registry basis."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-albite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearanceClaims"
      ],
      "referenceIds": [
        "handbook-albite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent common albite varieties. Values are not measured optical constants."
    }
  ],
  "appearance": [
    {
      "id": "white",
      "luster": "vitreous",
      "name": "White",
      "baseColor": "#eef0f2",
      "roughness": 0.15,
      "metalness": 0,
      "transmission": 0.6,
      "ior": 1.529,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    }
  ],
  "appearanceClaims": [
    {
      "id": "appearance.albite.color",
      "property": "color",
      "description": "Albite occurs white to gray, with bluish, greenish, or reddish colour reported.",
      "surfaceOrigin": "not-surface-specific",
      "disposition": "descriptive-only",
      "dispositionReason": "Colour range describes mineral appearance and does not define a measured renderer colour.",
      "typicality": "general"
    },
    {
      "id": "appearance.albite.diaphaneity",
      "property": "diaphaneity",
      "description": "Albite is reported as transparent to translucent.",
      "surfaceOrigin": "not-surface-specific",
      "disposition": "descriptive-only",
      "dispositionReason": "Diaphaneity does not directly determine the curated transmission value.",
      "typicality": "general"
    },
    {
      "id": "appearance.albite.luster",
      "property": "luster",
      "description": "Albite has vitreous luster, typically pearly on cleavage surfaces.",
      "surfaceOrigin": "not-surface-specific",
      "disposition": "descriptive-only",
      "dispositionReason": "The general luster observation has no growth-face selector.",
      "typicality": "general"
    },
    {
      "id": "appearance.albite.cleavage-pearly",
      "property": "cleavage-appearance",
      "description": "Albite cleavage surfaces are typically pearly.",
      "surfaceOrigin": "cleavage",
      "disposition": "descriptive-only",
      "dispositionReason": "Cleavage observations must not select generated growth faces.",
      "typicality": "general"
    },
    {
      "id": "appearance.albite.twinning-striae",
      "property": "twinning-appearance",
      "description": "Polysynthetic twinning can produce striae on {001} or {010} surfaces.",
      "surfaceOrigin": "twinning",
      "disposition": "blocked",
      "dispositionReason": "Twinning and its surface-origin semantics are not yet represented by the morphology renderer."
    }
  ],
  "habits": [
    {
      "id": "tabular",
      "name": "Tabular",
      "description": "Flattened parallel to {010}; pinacoid {010} dominant with {001} and {110} bounding the edges.",
      "forms": [
        {
          "id": "b",
          "label": "Pinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "c",
          "label": "Pinacoid {001}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 0,
            "l": 1
          },
          "development": 0.4
        },
        {
          "id": "m",
          "label": "Pinacoid {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0.4
        }
      ],
      "references": [
        {
          "id": "cod-2107372"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.4,
          -1.8,
          1.2
        ]
      }
    },
    {
      "id": "prismatic",
      "name": "Prismatic",
      "description": "Elongated blocky habit with {110} and {1-10} prisms more developed; {010} and {001} subordinate.",
      "forms": [
        {
          "id": "b",
          "label": "Pinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 0.7
        },
        {
          "id": "c",
          "label": "Pinacoid {001}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 0,
            "l": 1
          },
          "development": 0.6
        },
        {
          "id": "m",
          "label": "Pinacoid {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "z",
          "label": "Pinacoid {1-10}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": -1,
            "l": 0
          },
          "development": 1
        }
      ],
      "references": [
        {
          "id": "cod-2107372"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          0.9
        ]
      }
    }
  ]
});

export const GYPSUM = defineMineral({
  "id": "gypsum",
  "name": "Gypsum",
  "formula": "CaSO₄·2H₂O",
  "dataRevision": "sr8-1",
  "crystallography": {
    "crystalSystem": "monoclinic",
    "pointGroup": "2/m",
    "setting": "monoclinic-b",
    "spaceGroup": "I2/a",
    "unitCell": {
      "a": 5.67,
      "b": 15.201,
      "c": 6.533,
      "alpha": 90,
      "beta": 118.6,
      "gamma": 90
    }
  },
  "references": [
    {
      "id": "cod-5000039",
      "title": "Cole and Lancucki (1974), A refinement of the crystal structure of gypsum CaSO4.2H2O, Acta Crystallographica B30, 921-929",
      "url": "https://www.crystallography.net/cod/5000039.html",
      "notes": "COD CC0; space group I2/a (No. 15), unique axis b. Unit cell a=5.67, b=15.201, c=6.533 Å, beta=118.6 deg."
    },
    {
      "id": "handbook-gypsum-v1",
      "title": "Mineral Data Publishing, Gypsum, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/gypsum.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; luster is subvitreous, with pearly luster limited to {010} cleavage and silky luster to fibrous material."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-5000039"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "status": "curated",
      "derivation": "Habit form selections use standard monoclinic form indices in the I2/a cell basis. Development values, disabled forms, and preferred views are curated visualization choices, not measured growth parameters. The declared monoclinic-b setting selects the core registry basis with unique axis b."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-gypsum-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": ["appearanceClaims"],
      "referenceIds": ["handbook-gypsum-v1"],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters selected to represent common gypsum varieties. The supported vitreous category normalizes the reported subvitreous whole-crystal luster; pearly {010} cleavage and silky fibrous material are not transferred to whole-crystal presets. Values are not measured optical constants."
    }
  ],
  "appearance": [
    {
      "id": "colorless",
      "luster": "vitreous",
      "name": "Colorless",
      "baseColor": "#eef0f2",
      "roughness": 0.1,
      "metalness": 0,
      "transmission": 0.7,
      "ior": 1.521,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    },
    {
      "id": "selenite",
      "luster": "vitreous",
      "name": "Selenite",
      "baseColor": "#f0f0e0",
      "roughness": 0.08,
      "metalness": 0,
      "transmission": 0.75,
      "ior": 1.521,
      "absorptionColor": "#fff8e0",
      "absorptionDensity": 0.1
    }
  ],
  "appearanceClaims": [
    {"id":"appearance.gypsum.color","property":"color","description":"Gypsum is colorless or white and may be yellow, tan, blue, pink, brown, reddish brown, gray, or black when coloured by impurities.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"The colour range does not define a measured renderer colour.","typicality":"general"},
    {"id":"appearance.gypsum.diaphaneity","property":"diaphaneity","description":"Gypsum is reported as transparent to translucent.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"Diaphaneity does not directly determine the curated transmission value.","typicality":"general"},
    {"id":"appearance.gypsum.luster","property":"luster","description":"Gypsum has subvitreous luster.","surfaceOrigin":"not-surface-specific","disposition":"blocked","dispositionReason":"The current luster vocabulary does not distinguish subvitreous luster.","typicality":"general"},
    {"id":"appearance.gypsum.striations","property":"striations","description":"Gypsum crystals may be coarsely striated parallel to [001].","surfaceOrigin":"unknown","disposition":"candidate","dispositionReason":"The source does not establish a growth-face origin or assign the striations to a shipped growth form.","typicality":"general"},
    {"id":"appearance.gypsum.cleavage-pearly","property":"cleavage-appearance","description":"Gypsum has pearly luster on {010} cleavage surfaces.","surfaceOrigin":"cleavage","disposition":"descriptive-only","dispositionReason":"Cleavage observations must not select generated growth faces."},
    {"id":"appearance.gypsum.fibrous-silky","property":"fibrous-appearance","description":"Fibrous gypsum has silky luster.","surfaceOrigin":"aggregate-or-fibrous","disposition":"descriptive-only","dispositionReason":"Fibrous aggregate appearance must not be mapped onto an ordinary growth face."}
  ],
  "habits": [
    {
      "id": "tabular",
      "name": "Tabular (Selenite)",
      "description": "Clinopinacoid {010} dominant; flat tabular crystal bounded by {110} and {111}. The common selenite habit.",
      "forms": [
        {
          "id": "b",
          "label": "Clinopinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "m",
          "label": "Prism {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0.3
        },
        {
          "id": "o",
          "label": "Prism {111}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 1
          },
          "development": 0.3
        }
      ],
      "references": [
        {
          "id": "cod-5000039"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.4,
          -1.7,
          1.2
        ]
      }
    },
    {
      "id": "prismatic",
      "name": "Prismatic",
      "description": "Prism {110} dominant with clinodome {011} and prism {111}; elongated prismatic habit without prominent {010}.",
      "forms": [
        {
          "id": "b",
          "label": "Clinopinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "m",
          "label": "Prism {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "o",
          "label": "Prism {111}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 1
          },
          "development": 0.5
        },
        {
          "id": "d",
          "label": "Clinodome {011}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 1
          },
          "development": 0.5
        }
      ],
      "references": [
        {
          "id": "cod-5000039"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          0.75
        ]
      }
    }
  ]
});

export const FORSTERITE = defineMineral({
  "id": "forsterite",
  "name": "Forsterite",
  "formula": "Mg₂SiO₄",
  "dataRevision": "sr8-1",
  "crystallography": {
    "crystalSystem": "orthorhombic",
    "pointGroup": "mmm",
    "setting": "orthorhombic-standard",
    "spaceGroup": "Pbnm",
    "unitCell": {
      "a": 4.756,
      "b": 10.207,
      "c": 5.98,
      "alpha": 90,
      "beta": 90,
      "gamma": 90
    }
  },
  "references": [
    {
      "id": "cod-9000319",
      "title": "Smyth and Hazen (1973), American Mineralogist 58, 588-593",
      "url": "https://www.crystallography.net/cod/9000319.html",
      "notes": "COD CC0; forsterite endmember, space group Pbnm (No. 62). Unit cell a=4.756, b=10.207, c=5.980 Å."
    },
    {
      "id": "handbook-forsterite-v1",
      "title": "Mineral Data Publishing, Forsterite, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/forsterite.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source describes luster as vitreous."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-9000319"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "status": "curated",
      "derivation": "Habit form selections use standard orthorhombic form indices in the Pbnm cell basis. Development values, disabled forms, and preferred views are curated visualization choices, not measured growth parameters. The declared standard setting selects the core registry basis."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-forsterite-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": ["appearanceClaims"],
      "referenceIds": ["handbook-forsterite-v1"],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent common olivine varieties. Values are not measured optical constants."
    }
  ],
  "appearance": [
    {
      "id": "olive",
      "luster": "vitreous",
      "name": "Olive green",
      "baseColor": "#6b8e23",
      "roughness": 0.3,
      "metalness": 0,
      "transmission": 0.3,
      "ior": 1.635,
      "absorptionColor": "#4a6b18",
      "absorptionDensity": 0.8
    },
    {
      "id": "colorless",
      "luster": "vitreous",
      "name": "Colorless",
      "baseColor": "#eef0f2",
      "roughness": 0.1,
      "metalness": 0,
      "transmission": 0.8,
      "ior": 1.635,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    }
  ],
  "appearanceClaims": [
    {"id":"appearance.forsterite.color","property":"color","description":"Forsterite occurs green, yellowish, lemon-yellow, white, grayish, or blue-gray.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"The colour range does not define a measured renderer colour.","typicality":"general"},
    {"id":"appearance.forsterite.diaphaneity","property":"diaphaneity","description":"Forsterite is reported as transparent to translucent.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"Diaphaneity does not directly determine the curated transmission value.","typicality":"general"},
    {"id":"appearance.forsterite.luster","property":"luster","description":"Forsterite has vitreous luster.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"The whole-mineral luster observation has no growth-face selector.","typicality":"general"},
    {"id":"appearance.forsterite.striations","property":"striations","description":"Euhedral or subhedral forsterite crystals may have striations parallel to their elongation.","surfaceOrigin":"unknown","disposition":"blocked","dispositionReason":"The source does not establish a growth-face origin, and the crystallographic elongation direction has not been resolved for the shipped habits."}
  ],
  "habits": [
    {
      "id": "tabular",
      "name": "Tabular",
      "description": "Pinacoid {010} dominant; flattened tabular crystal bounded by {110} and {001}.",
      "forms": [
        {
          "id": "b",
          "label": "Pinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "m",
          "label": "Prism {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 0.4
        },
        {
          "id": "c",
          "label": "Pinacoid {001}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 0,
            "l": 1
          },
          "development": 0.5
        }
      ],
      "references": [
        {
          "id": "cod-9000319"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    },
    {
      "id": "prismatic",
      "name": "Prismatic",
      "description": "Prism {110} dominant with subordinate {010} and prism {021}; elongated prismatic habit.",
      "forms": [
        {
          "id": "b",
          "label": "Pinacoid {010}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 1,
            "l": 0
          },
          "development": 0.5
        },
        {
          "id": "m",
          "label": "Prism {110}",
          "indices": {
            "notation": "miller",
            "h": 1,
            "k": 1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "c",
          "label": "Pinacoid {001}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 0,
            "l": 1
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "s",
          "label": "Prism {021}",
          "indices": {
            "notation": "miller",
            "h": 0,
            "k": 2,
            "l": 1
          },
          "development": 0.4
        }
      ],
      "references": [
        {
          "id": "cod-9000319"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.4,
          -2,
          0.8
        ]
      }
    }
  ]
});

export const BERYL = defineMineral({
  "id": "beryl",
  "name": "Beryl",
  "formula": "Be₃Al₂Si₆O₁₈",
  "dataRevision": "sr8-1",
  "crystallography": {
    "crystalSystem": "hexagonal",
    "pointGroup": "6/mmm",
    "setting": "hexagonal-standard",
    "spaceGroup": "P6/mcc",
    "unitCell": {
      "a": 9.208,
      "b": 9.208,
      "c": 9.188,
      "alpha": 90,
      "beta": 90,
      "gamma": 120
    }
  },
  "references": [
    {
      "id": "cod-9001018",
      "title": "Hazen, Au and Finger (1986), High-pressure crystal chemistry of beryl, American Mineralogist 71, 977-984",
      "url": "https://www.crystallography.net/cod/9001018.html",
      "notes": "COD CC0; space group P6/mcc (No. 192). Ambient-pressure sample (0.001 kbar). Unit cell a=9.208, c=9.188 Å."
    },
    {
      "id": "handbook-beryl-v1",
      "title": "Mineral Data Publishing, Beryl, version 1",
      "url": "https://www.handbookofmineralogy.org/pdfs/beryl.pdf",
      "notes": "Publicly readable; accessed 2026-09-19. Used as a factual citation only; the source reports a vitreous-to-resinous luster range. Current presets use the supported vitreous category."
    }
  ],
  "provenance": [
    {
      "coverage": [
        "crystallography"
      ],
      "referenceIds": [
        "cod-9001018"
      ],
      "status": "reported"
    },
    {
      "coverage": [
        "habits"
      ],
      "status": "curated",
      "derivation": "Habit form selections use standard hexagonal form indices in Miller-Bravais notation. Development values, disabled forms, and preferred views are curated visualization choices, not measured growth parameters. The declared hexagonal setting selects the core registry basis."
    },
    {
      "coverage": [
        "appearance.*.luster"
      ],
      "referenceIds": [
        "handbook-beryl-v1"
      ],
      "status": "reported"
    },
    {
      "coverage": ["appearanceClaims"],
      "referenceIds": ["handbook-beryl-v1"],
      "status": "reported"
    },
    {
      "coverage": [
        "appearance"
      ],
      "status": "curated",
      "derivation": "Appearance presets use curated visualization parameters (base color, roughness, metalness, transmission, IOR, absorption color and density) selected to represent common beryl varieties (emerald, aquamarine, goshenite). IOR values are representative approximations, not measured optical constants."
    }
  ],
  "appearance": [
    {
      "id": "emerald",
      "luster": "vitreous",
      "name": "Emerald",
      "baseColor": "#2d8a4a",
      "roughness": 0.08,
      "metalness": 0,
      "transmission": 0.7,
      "ior": 1.577,
      "absorptionColor": "#1a6b3a",
      "absorptionDensity": 0.6
    },
    {
      "id": "aquamarine",
      "luster": "vitreous",
      "name": "Aquamarine",
      "baseColor": "#5bb8d4",
      "roughness": 0.06,
      "metalness": 0,
      "transmission": 0.8,
      "ior": 1.577,
      "absorptionColor": "#3a98b4",
      "absorptionDensity": 0.4
    },
    {
      "id": "goshenite",
      "luster": "vitreous",
      "name": "Goshenite",
      "baseColor": "#eef0f2",
      "roughness": 0.05,
      "metalness": 0,
      "transmission": 0.9,
      "ior": 1.577,
      "absorptionColor": "#ffffff",
      "absorptionDensity": 0
    }
  ],
  "appearanceClaims": [
    {"id":"appearance.beryl.color","property":"color","description":"Beryl occurs colorless, white, blue, green, yellow, rose to red, and may be zoned.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"The reported colour range and zoning do not define measured renderer colours.","typicality":"general"},
    {"id":"appearance.beryl.diaphaneity","property":"diaphaneity","description":"Beryl is reported as transparent to translucent.","surfaceOrigin":"not-surface-specific","disposition":"descriptive-only","dispositionReason":"Diaphaneity does not directly determine the curated transmission value.","typicality":"general"},
    {"id":"appearance.beryl.luster","property":"luster","description":"Beryl has vitreous to resinous luster.","surfaceOrigin":"not-surface-specific","disposition":"blocked","dispositionReason":"The current luster vocabulary has no resinous category, and a material mapping needs review.","typicality":"general"}
  ],
  "habits": [
    {
      "id": "prismatic",
      "name": "Prismatic",
      "description": "Hexagonal prism {10-10} dominant with basal pinacoid {0001} termination; the common long-prismatic beryl habit.",
      "forms": [
        {
          "id": "m",
          "label": "Prism {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 1
        },
        {
          "id": "c",
          "label": "Basal pinacoid {0001}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 0,
            "i": 0,
            "l": 1
          },
          "development": 0.5
        },
        {
          "id": "p",
          "label": "Dipyramid {10-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 1
          },
          "development": 0,
          "enabled": false
        }
      ],
      "references": [
        {
          "id": "cod-9001018"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          0.8
        ]
      }
    },
    {
      "id": "short-prismatic",
      "name": "Short prismatic",
      "description": "Prism {10-10} with dipyramid {10-11} modifying the terminations; shorter, more equant habit.",
      "forms": [
        {
          "id": "m",
          "label": "Prism {10-10}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 0
          },
          "development": 0.7
        },
        {
          "id": "c",
          "label": "Basal pinacoid {0001}",
          "indices": {
            "notation": "miller-bravais",
            "h": 0,
            "k": 0,
            "i": 0,
            "l": 1
          },
          "development": 0,
          "enabled": false
        },
        {
          "id": "p",
          "label": "Dipyramid {10-11}",
          "indices": {
            "notation": "miller-bravais",
            "h": 1,
            "k": 0,
            "i": -1,
            "l": 1
          },
          "development": 0.6
        }
      ],
      "references": [
        {
          "id": "cod-9001018"
        }
      ],
      "preferredView": {
        "cameraDirection": [
          1.5,
          -2,
          1.1
        ]
      }
    }
  ]
});
