// Generated by scripts/generate-m5-registry.mjs.
export const M5_INTEGRITY = {
  "sourceSha256": "bf1ab8a74e1d275e20ee4145bd409b62b5295e680599d3a112a41d396bde56bd",
  "artifactSha256": "c7481c953899db94954b83c1071b7f0291e3c0511bfe283a52fbd05b1d8d5c5b",
  "generator": "scripts/generate-m5-registry.mjs"
} as const;
