// Generated by scripts/generate-m5-registry.mjs; see LICENSE.spglib.
export const M5_SUBSETS = [
  {
    "id": "point-group:m-3:cubic-standard",
    "pointGroup": "m-3",
    "setting": "cubic-standard",
    "crystalSystem": "cubic",
    "hallNumber": 501,
    "spaceGroupNumber": 205,
    "basis": "Pa-3; conventional cubic axes",
    "operations": [
      {
        "id": "hall-501-point-00",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-501-point-01",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-501-point-02",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-501-point-03",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-501-point-04",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ],
          [
            -1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-05",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ],
          [
            1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-06",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ],
          [
            -1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-07",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ],
          [
            1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-08",
        "linear": [
          [
            0,
            0,
            -1
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-09",
        "linear": [
          [
            0,
            0,
            -1
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-10",
        "linear": [
          [
            0,
            0,
            -1
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-11",
        "linear": [
          [
            0,
            0,
            -1
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-12",
        "linear": [
          [
            0,
            0,
            1
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-13",
        "linear": [
          [
            0,
            0,
            1
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-14",
        "linear": [
          [
            0,
            0,
            1
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-15",
        "linear": [
          [
            0,
            0,
            1
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-16",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ],
          [
            -1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-17",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ],
          [
            1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-18",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ],
          [
            -1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-19",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ],
          [
            1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-501-point-20",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-501-point-21",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-501-point-22",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-501-point-23",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      }
    ]
  },
  {
    "id": "point-group:4/mmm:tetragonal-standard",
    "pointGroup": "4/mmm",
    "setting": "tetragonal-standard",
    "crystalSystem": "tetragonal",
    "hallNumber": 426,
    "spaceGroupNumber": 141,
    "basis": "I41/amd origin choice 1; conventional tetragonal axes",
    "operations": [
      {
        "id": "hall-426-point-00",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-426-point-01",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-426-point-02",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-426-point-03",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-426-point-04",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-426-point-05",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-426-point-06",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-426-point-07",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-426-point-08",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-426-point-09",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-426-point-10",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-426-point-11",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-426-point-12",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-426-point-13",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-426-point-14",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-426-point-15",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      }
    ]
  },
  {
    "id": "point-group:-3m:hexagonal-standard",
    "pointGroup": "-3m",
    "setting": "hexagonal-standard",
    "crystalSystem": "trigonal",
    "hallNumber": 460,
    "spaceGroupNumber": 167,
    "basis": "R-3c:H; obverse R-centered hexagonal axes",
    "operations": [
      {
        "id": "hall-460-point-00",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            -1,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-460-point-01",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-460-point-02",
        "linear": [
          [
            -1,
            1,
            0
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-460-point-03",
        "linear": [
          [
            -1,
            1,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-460-point-04",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-460-point-05",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            1,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-460-point-06",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            -1,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-460-point-07",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-460-point-08",
        "linear": [
          [
            1,
            -1,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-460-point-09",
        "linear": [
          [
            1,
            -1,
            0
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-460-point-10",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-460-point-11",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            1,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      }
    ]
  },
  {
    "id": "point-group:-3m:rhombohedral-standard",
    "pointGroup": "-3m",
    "setting": "rhombohedral-standard",
    "crystalSystem": "trigonal",
    "hallNumber": 461,
    "spaceGroupNumber": 167,
    "basis": "R-3c:R; primitive rhombohedral axes",
    "operations": [
      {
        "id": "hall-461-point-00",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-461-point-01",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ],
          [
            0,
            -1,
            0
          ]
        ]
      },
      {
        "id": "hall-461-point-02",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-461-point-03",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ],
          [
            -1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-461-point-04",
        "linear": [
          [
            0,
            0,
            -1
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ]
        ]
      },
      {
        "id": "hall-461-point-05",
        "linear": [
          [
            0,
            0,
            -1
          ],
          [
            0,
            -1,
            0
          ],
          [
            -1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-461-point-06",
        "linear": [
          [
            0,
            0,
            1
          ],
          [
            0,
            1,
            0
          ],
          [
            1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-461-point-07",
        "linear": [
          [
            0,
            0,
            1
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ]
        ]
      },
      {
        "id": "hall-461-point-08",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ],
          [
            1,
            0,
            0
          ]
        ]
      },
      {
        "id": "hall-461-point-09",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-461-point-10",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ],
          [
            0,
            1,
            0
          ]
        ]
      },
      {
        "id": "hall-461-point-11",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      }
    ]
  },
  {
    "id": "point-group:6/mmm:hexagonal-standard",
    "pointGroup": "6/mmm",
    "setting": "hexagonal-standard",
    "crystalSystem": "hexagonal",
    "hallNumber": 486,
    "spaceGroupNumber": 192,
    "basis": "P6/mcc; conventional hexagonal axes",
    "operations": [
      {
        "id": "hall-486-point-00",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            -1,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-01",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            -1,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-486-point-02",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-03",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-486-point-04",
        "linear": [
          [
            -1,
            1,
            0
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-05",
        "linear": [
          [
            -1,
            1,
            0
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-486-point-06",
        "linear": [
          [
            -1,
            1,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-07",
        "linear": [
          [
            -1,
            1,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-486-point-08",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-09",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            -1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-486-point-10",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            1,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-11",
        "linear": [
          [
            0,
            -1,
            0
          ],
          [
            1,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-486-point-12",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            -1,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-13",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            -1,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-486-point-14",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-15",
        "linear": [
          [
            0,
            1,
            0
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-486-point-16",
        "linear": [
          [
            1,
            -1,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-17",
        "linear": [
          [
            1,
            -1,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-486-point-18",
        "linear": [
          [
            1,
            -1,
            0
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-19",
        "linear": [
          [
            1,
            -1,
            0
          ],
          [
            1,
            0,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-486-point-20",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-21",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-486-point-22",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            1,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-486-point-23",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            1,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      }
    ]
  },
  {
    "id": "point-group:mmm:orthorhombic-standard",
    "pointGroup": "mmm",
    "setting": "orthorhombic-standard",
    "crystalSystem": "orthorhombic",
    "hallNumber": 294,
    "spaceGroupNumber": 62,
    "basis": "Pbnm (cab setting of No. 62); orthorhombic axes",
    "operations": [
      {
        "id": "hall-294-point-00",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-294-point-01",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-294-point-02",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-294-point-03",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-294-point-04",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-294-point-05",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-294-point-06",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-294-point-07",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      }
    ]
  },
  {
    "id": "point-group:2/m:monoclinic-b",
    "pointGroup": "2/m",
    "setting": "monoclinic-b",
    "crystalSystem": "monoclinic",
    "hallNumber": 90,
    "spaceGroupNumber": 15,
    "basis": "C2/c; unique axis b, cell choice 1",
    "operations": [
      {
        "id": "hall-90-point-00",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-90-point-01",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-90-point-02",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      },
      {
        "id": "hall-90-point-03",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      }
    ]
  },
  {
    "id": "point-group:-1:triclinic-standard",
    "pointGroup": "-1",
    "setting": "triclinic-standard",
    "crystalSystem": "triclinic",
    "hallNumber": 2,
    "spaceGroupNumber": 2,
    "basis": "Inversion and identity; valid in primitive or centered triclinic axes",
    "operations": [
      {
        "id": "hall-2-point-00",
        "linear": [
          [
            -1,
            0,
            0
          ],
          [
            0,
            -1,
            0
          ],
          [
            0,
            0,
            -1
          ]
        ]
      },
      {
        "id": "hall-2-point-01",
        "linear": [
          [
            1,
            0,
            0
          ],
          [
            0,
            1,
            0
          ],
          [
            0,
            0,
            1
          ]
        ]
      }
    ]
  }
] as const;
