// Generated by scripts/generate-m3-registry.mjs; see LICENSE.spglib.
import type { PointOperation } from "../symmetry.js";
export const TRIGONAL_32_OPERATIONS: readonly PointOperation[] = [
  {
    "id": "32-00",
    "linear": [
      [
        1,
        0,
        0
      ],
      [
        0,
        1,
        0
      ],
      [
        0,
        0,
        1
      ]
    ]
  },
  {
    "id": "32-01",
    "linear": [
      [
        0,
        -1,
        0
      ],
      [
        1,
        -1,
        0
      ],
      [
        0,
        0,
        1
      ]
    ]
  },
  {
    "id": "32-02",
    "linear": [
      [
        -1,
        1,
        0
      ],
      [
        -1,
        0,
        0
      ],
      [
        0,
        0,
        1
      ]
    ]
  },
  {
    "id": "32-03",
    "linear": [
      [
        -1,
        0,
        0
      ],
      [
        -1,
        1,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "id": "32-04",
    "linear": [
      [
        0,
        1,
        0
      ],
      [
        1,
        0,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "id": "32-05",
    "linear": [
      [
        1,
        -1,
        0
      ],
      [
        0,
        -1,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  }
];
